var files = require('./files');

var initialState = {
    _version: 0,
    parsedSource: files.html.parsedSource,
    activeVariant: 'light',
    selectedGroup: 'Normal',
    hoverGroup: undefined,
    activeColor: 'foreground',
    activeFile: 'html',
    activePane: 'light',
    exportName: 'my-default',
    ExportedSource: undefined,
    postProcess: {
        dark: {
            brightness: 0,
            saturation: 0
        },
        light: {
            brightness: 0,
            saturation: 0
        }
    },
    componentsVisibility: {
        tabLine: 'show',
        lineNumbers: 'show',
        statusLine: 'show'
    },
    sectionsVisibility: {
        variant: 'show',
        selectedGroup: 'show',
        color: 'show',
        highlight: 'show',
        modifiedGroups: 'hide',
        components: 'hide',
        postProcess: 'hide',
        export_: 'show',
        dangerZone: 'hide'
    },
    light: {
        ColorColumn: {backgroundColor: '#eeeeee'},
        Comment: {color: '#cccccc'},
        Conceal: {color: '#777777'},
        Conditional: {color: '#777777'},
        Constant: {color: '#999999'},
        Cursor: {highlight: 'reverse'},
        CursorColumn: {backgroundColor: '#eeeeee'},
        CursorLine: {backgroundColor: '#eeeeee'},
        CursorLineNr: {color: '#999999'},
        DiffAdd: {},
        DiffChange: {},
        DiffDelete: {color: '#cc3333'},
        DiffText: {},
        Directory: {color: '#777777'},
        Error: {},
        ErrorMsg: {color: '#cc3333'},
        FoldColumn: {color: '#cccccc'},
        Folded: {color: '#cccccc'},
        Ignore: {},
        IncSearch: {backgroundColor: '#dddddd'},
        LineNr: {color: '#cccccc'},
        MatchParen: {backgroundColor: '#dddddd'},
        ModeMsg: {},
        MoreMsg: {},
        NonText: {color: '#cccccc'},
        Normal: {color: '#000000', backgroundColor: '#ffffff'},
        Number: {color: '#999999'},
        Pmenu: {backgroundColor: '#eeeeee'},
        PmenuSbar: {},
        PmenuSel: {backgroundColor: '#dddddd'},
        PmenuThumb: {},
        Question: {},
        Search: {backgroundColor: '#eeeeee'},
        SignColumn: {color: '#cccccc'},
        Special: {color: '#777777'},
        SpecialKey: {color: '#cccccc'},
        SpellBad: {color: '#cc3333'},
        SpellCap: {},
        SpellLocal: {},
        SpellRare: {},
        Statement: {color: '#777777'},
        StatusLine: {color: '#777777', backgroundColor: '#eeeeee'},
        StatusLineNC: {color: '#bbbbbb', backgroundColor: '#eeeeee'},
        StorageClass: {color: '#777777'},
        String: {color: '#999999'},
        TabLine: {color: '#bbbbbb', backgroundColor: '#eeeeee'},
        TabLineFill: {backgroundColor: '#eeeeee'},
        TabLineSel: {color: '#777777', backgroundColor: '#eeeeee'},
        Title: {},
        Todo: {highlight: 'standout'},
        Type: {color: '#777777'},
        Underlined: {},
        VertSplit: {color: '#eeeeee'},
        Visual: {backgroundColor: '#dddddd'},
        VisualNOS: {},
        WarningMsg: {},
        WildMenu: {backgroundColor: '#dddddd'},
        lCursor: {}
    },
    dark: {
        ColorColumn: {backgroundColor: '#222222'},
        Comment: {color: '#555555'},
        Conceal: {color: '#999999'},
        Conditional: {color: '#999999'},
        Constant: {color: '#777777'},
        Cursor: {highlight: 'reverse'},
        CursorColumn: {backgroundColor: '#222222'},
        CursorLine: {backgroundColor: '#222222'},
        CursorLineNr: {color: '#777777'},
        DiffAdd: {},
        DiffChange: {},
        DiffDelete: {color: '#cc3333'},
        DiffText: {},
        Directory: {color: '#999999'},
        Error: {},
        ErrorMsg: {color: '#cc3333'},
        FoldColumn: {color: '#555555'},
        Folded: {color: '#555555'},
        Ignore: {},
        IncSearch: {backgroundColor: '#555555'},
        LineNr: {color: '#555555'},
        MatchParen: {backgroundColor: '#555555'},
        ModeMsg: {},
        MoreMsg: {},
        NonText: {color: '#555555'},
        Normal: {color: '#aaaaaa', backgroundColor: '#000000'},
        Number: {color: '#777777'},
        Pmenu: {backgroundColor: '#222222'},
        PmenuSbar: {},
        PmenuSel: {backgroundColor: '#333333'},
        PmenuThumb: {},
        Question: {},
        Search: {backgroundColor: '#333333'},
        SignColumn: {color: '#555555'},
        Special: {color: '#999999'},
        SpecialKey: {color: '#555555'},
        SpellBad: {color: '#cc3333'},
        SpellCap: {},
        SpellLocal: {},
        SpellRare: {},
        Statement: {color: '#999999'},
        StatusLine: {color: '#999999', backgroundColor: '#222222'},
        StatusLineNC: {color: '#777777', backgroundColor: '#222222'},
        StorageClass: {color: '#999999'},
        String: {color: '#777777'},
        TabLine: {color: '#777777', backgroundColor: '#222222'},
        TabLineFill: {backgroundColor: '#222222'},
        TabLineSel: {color: '#999999', backgroundColor: '#222222'},
        Title: {},
        Todo: {highlight: 'standout'},
        Type: {color: '#999999'},
        Underlined: {},
        VertSplit: {color: '#333333'},
        Visual: {backgroundColor: '#555555'},
        VisualNOS: {},
        WarningMsg: {},
        WildMenu: {backgroundColor: '#333333'},
        lCursor: {}
    }
};

module.exports = initialState;
